gems:
  - jekyll/scholar
  - rdiscount
  - jekyll-org-mode-converter


gems: [jekyll-paginate, jekyll-feed]
paginate: 4
paginate_path: "/blog/page:num/"

highlighter: rouge
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

exclude: ['README.org']

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: pedroguilherme.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"


image: /images/default.jpg

url: "http://greedblink.github.io/"

authors: 
  jonatha: 
    name: Jonatha Azevedo
    display_name: Jonatha
    email: jonatha.costa@fgv.br
    twitter: 
    github: GreedBlink
  
    fernando: 
      name: Fernando Teixeira
      display_name: Fernando
      email: fernando.teixeira@fgv.br
      twitter: 
      github: GreedBlink
    
    lucas:
     name: lucas Farias
     display_name: Lucas
     email: Lucas.farias@fgv.br
     twitter: 
     github: 
     
    Pedro:
     name: Pedro Costa 
     display_name: Pedro
     email: pedro.guilherme@fgv.br
     twitter: 
     github: 




