encoding: UTF-8
name: Pedro Costa Ferreira
markdown: kramdown

url: http://pedrocostaferreira.github.io

author :
  name : Pedro Costa Ferreira
  givenName: pedrocostaferreira
  familyName: Pedro
  github: pedrocostaferreira
  email : pedro.gulherme@fgv.br
 


disqus:
  sitename: qxd # This is the shortname of the disqus site id to display disqus comments below posts.
  
gems: ['jekyll/scholar']

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
